### 1.Setup

In [119]:
%pip install -q pandas numpy

Note: you may need to restart the kernel to use updated packages.

In [120]:
import numpy as np
import pandas as pd

# pd.set_option("display.max_columns",None)
pd.set_option("display.max_columns",50)

**2.Load the dataset**

titanic_dataset.csv

In [121]:
df = pd.read_csv("titanic_dataset.csv")

In [122]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [123]:
df.shape

(891, 15)

**3. Adding few columns for demonstrating data issues**

In [124]:
# 1 to 891
# np.arange(1,891)

# ID like column
np.arange(1,891+1)
df["passenger_id"] = np.arange(1,len(df)+1)

# constant column
df["constant_col"] = 1

In [125]:
df["embark_town_dirty"]  = df["embark_town"].copy()

In [126]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_col,embark_town_dirty
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton

In [127]:
df["age"].dtype

dtype('float64')

In [128]:
df["age"] = df["age"].astype(float)

In [129]:
df["age"].dtype

dtype('float64')

In [130]:
df["embark_town_dirty"].isnull().sum()

np.int64(2)

In [131]:
df[df["embark_town_dirty"].isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_col,embark_town_dirty
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,62,1,NaN
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,830,1,NaN

In [132]:
sample_idx = df["embark_town_dirty"].dropna().sample(6,random_state=42).index

In [133]:
sample_idx

Index([281, 435, 39, 418, 585, 804], dtype='int64')

In [134]:
# apply simple dirty transformations
df.loc[sample_idx[0:2],"embark_town_dirty"] = df.loc[sample_idx[0:2],"embark_town_dirty"].str.upper()
df.loc[sample_idx[2:4],"embark_town_dirty"] = df.loc[sample_idx[2:4],"embark_town_dirty"].str.strip().apply(lambda x:f" {x} ")
df.loc[sample_idx[4:6],"embark_town_dirty"] = "unknown"

In [135]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_col,embark_town_dirty
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton

In [136]:
df["age"].dtype

dtype('float64')

In [137]:
df.iloc[281]

survived                       0
pclass                         3
sex                         male
age                         28.0
sibsp                          0
parch                          0
fare                      7.8542
embarked                       S
class                      Third
who                          man
adult_male                  True
deck                         NaN
embark_town          Southampton
alive                         no
alone                       True
passenger_id                 282
constant_col                   1
embark_town_dirty    SOUTHAMPTON
Name: 281, dtype: object

In [138]:
df.iloc[281]["embark_town_dirty"]

'SOUTHAMPTON'

In [139]:
df.iloc[435]

survived                       1
pclass                         1
sex                       female
age                         14.0
sibsp                          1
parch                          2
fare                       120.0
embarked                       S
class                      First
who                        child
adult_male                 False
deck                           B
embark_town          Southampton
alive                        yes
alone                      False
passenger_id                 436
constant_col                   1
embark_town_dirty    SOUTHAMPTON
Name: 435, dtype: object

In [140]:
df.iloc[585]

survived                       1
pclass                         1
sex                       female
age                         18.0
sibsp                          0
parch                          2
fare                       79.65
embarked                       S
class                      First
who                        woman
adult_male                 False
deck                           E
embark_town          Southampton
alive                        yes
alone                      False
passenger_id                 586
constant_col                   1
embark_town_dirty        unknown
Name: 585, dtype: object

### 4. Data quality checks

Quick checklist:
1. Basic dataset overview
2. Mising values summary
3. Duplicates
4. Data Type Validation
5. Constant and quasi constant column
6. ID like Column
7. String inconsistencies
8. High null columns
9. High zero columns (for numeric features)

**4.1. Basic Dataset overview**

In [141]:
print(df.shape)
print("-"*50)
print(df.dtypes)
print("-"*50)
print(df.info())

(891, 18)
--------------------------------------------------
survived               int64
pclass                 int64
sex                      str
age                  float64
sibsp                  int64
parch                  int64
fare                 float64
embarked                 str
class                    str
who                      str
adult_male              bool
deck                     str
embark_town              str
alive                    str
alone                   bool
passenger_id           int64
constant_col           int64
embark_town_dirty        str
dtype: object
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   survived           891 non-null    int64
 1   pclass             891 non-null    int64
 2   sex                891 non-null    str
 3   age                714 non-null    float64
 4   sibsp              891 non-null    int64
 5   parch              891 non-null    int64
 6   fare               891 non-null    float64
 7   embarked           889 non-null    str
 8   class              891 non-null    str
 9   who                891 non-null    str
 10  adult_male         891 non-null    bool
 11  deck               203 non-null    str
 12  embark_town        889 non-null    str
 13  alive              891 non-null    str
 14  alone              891 non-null    bool
 15  passenger_id       891 non-null    int64
 16  constant_col       891 non-null    int64
 17  embark_town_dirty  889 non-null    str
dtypes: bool(2), float64(2), int64(6), str(8)
memory usage: 113.2 KB
None

In [142]:
df.dtypes

survived               int64
pclass                 int64
sex                      str
age                  float64
sibsp                  int64
parch                  int64
fare                 float64
embarked                 str
class                    str
who                      str
adult_male              bool
deck                     str
embark_town              str
alive                    str
alone                   bool
passenger_id           int64
constant_col           int64
embark_town_dirty        str
dtype: object

In [143]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'passenger_id', 'constant_col', 'embark_town_dirty'],
      dtype='str')

In [144]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   88
sibsp                  7
parch                  7
fare                 248
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
passenger_id         891
constant_col           1
embark_town_dirty      7
dtype: int64

In [145]:
df.describe()

,survived,pclass,age,sibsp,parch,fare,passenger_id,constant_col
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.0
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,446.000000,1.0
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,257.353842,0.0
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000,1.0
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,223.500000,1.0
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,446.000000,1.0
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,668.500000,1.0
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,891.000000,1.0

In [146]:
df["passenger_id"]

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: passenger_id, Length: 891, dtype: int64

**4.2.Missing values summary**

In [147]:
df.isna().sum()

survived               0
pclass                 0
sex                    0
age                  177
sibsp                  0
parch                  0
fare                   0
embarked               2
class                  0
who                    0
adult_male             0
deck                 688
embark_town            2
alive                  0
alone                  0
passenger_id           0
constant_col           0
embark_town_dirty      2
dtype: int64

In [148]:
missing_count = df.isna().sum().sort_values(ascending=False)
missing_percent = (df.isna().mean() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame(
    {
        "missing_count" : missing_count,
        "missing_percent" : missing_percent
    }
)
print("Missing Values Summary")
missing_summary


# 688/891 = 0.77216610549943883277216610549944 * 100

Missing Values Summary

                   missing_count  missing_percent
deck                         688        77.216611
age                          177        19.865320
embark_town_dirty              2         0.224467
embarked                       2         0.224467
embark_town                    2         0.224467
survived                       0         0.000000
pclass                         0         0.000000
parch                          0         0.000000
sibsp                          0         0.000000
sex                            0         0.000000
who                            0         0.000000
class                          0         0.000000
fare                           0         0.000000
adult_male                     0         0.000000
alive                          0         0.000000
alone                          0         0.000000
passenger_id                   0         0.000000
constant_col                   0         0.000000

**4.3 Duplicates**

In [149]:
duplicates_mask = df.duplicated()
num_duplicates = duplicates_mask.sum()
print("Number of duplicate rows:",num_duplicates)

Number of duplicate rows: 0

In [150]:
pd.Series([False,True,True,False,False]).sum()

np.int64(2)

**4.3 Data Type Validation**

In [151]:
expected_types = {
    "survived": "int64",
    "pclass" : "int64", 
    "sex" : "category",
    "age" : "float64",
    "fare" : "float64",
    "embark_town" : "category",
    "passenger_id" : "int64"
}
for col, expected in expected_types.items():
    print(col,expected)

survived int64
pclass int64
sex category
age float64
fare float64
embark_town category
passenger_id int64

In [152]:
expected_types = {
    "survived": "int64",
    "pclass" : "int64", 
    "sex" : "category",
    "age" : "float64",
    "fare" : "float64",
    "embark_town" : "category",
    "passenger_id" : "int64"
}

print("Data Type Validation")
for col,expected in expected_types.items():
    if col in df.columns:
        actual=df[col].dtype
        print(f"{col}: actual={actual}, expected={expected}")

Data Type Validation
survived: actual=int64, expected=int64
pclass: actual=int64, expected=int64
sex: actual=str, expected=category
age: actual=float64, expected=float64
fare: actual=float64, expected=float64
embark_town: actual=str, expected=category
passenger_id: actual=int64, expected=int64

In [153]:
# example of fixing a data type if needed
# df["pclass"] = df["pclass"].astype("int64")

**4.5. Constant & Quasi-Constant Columns**

In [154]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   88
sibsp                  7
parch                  7
fare                 248
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
passenger_id         891
constant_col           1
embark_town_dirty      7
dtype: int64

In [155]:
# df.unique
# If df is a pandas DataFrame, df.unique() is not valid because unique() works on a Series, not the whole DataFrame.
# df['column_name'].unique()

In [159]:
n_rows = len(df)
nunique = df.nunique()

constant_cols = nunique[nunique == 1].index.to_list()
print("Constant columns:",constant_cols)

# quasi constant columns
quasi_constant_cols = []

for col in df.columns:
    top_freq = df[col].value_counts(normalize=True,dropna=False).values[0]
    if top_freq > 0.95 and col not in constant_cols:
        quasi_constant_cols.append(col)
print("Quassi constant columns (top value more than 95 percent:)",quasi_constant_cols)

Constant columns: ['constant_col']
Quassi constant columns (top value more than 95 percent:) []